# Generated by Django 3.2 on 2021-05-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20210521_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
